### PR TITLE
Sprint 16 Ergebnisse

### PR DESCRIPTION
**Pull request by bastienMPDL**
* Erweiterung der API
* Implementierung von Spaces
* Bug Fixing

### CODE REVIEW

**Comment by xrotwang** [comment]
Maybe merging into imeji-community/imeji more often would be more transparent? I guess there's no way to review a pull request this big.

**Comment by xrotwang** [comment]
And another tip to make pull requests easier to follow: You may want to use [git pull --rebase ...](http://gitready.com/advanced/2009/02/11/pull-with-rebase.html) when updating your local clones to avoid cluttering the history with these automatic *Merge branch ...* commits.

**Comment by bastienMPDL** [comment]
The Idea is to make pull Request as often as possible (every 2 weeks). 
But this times we had many issues which postponed it.
Thanks for the tip with the rebase option. I'm not sure if it would help us is this case, since there is no big activity in community repository.

**Comment by xrotwang** [comment]
I think it would also help making https://github.com/MPDL-Innovations/imeji/commits/develop easier to follow.

**Pull request merged**
